### ISSUE TITLE
restart_process only works for amd64 containers

### ISSUE THREAD

**Issue by milas** [tilt-dev/tilt-extensions#127]
Both `tilt-restart-wrapper` and `entr` are only compiled for `amd64`, so will result in exec errors if used for an ARM container (e.g. pushing to a k3s cluster on a Raspberry Pi).

We should either publish multi-arch images for `tiltdev/restart-helper` or update documentation to note that this is only supported for `amd64` targets.

**Comment by swarupdonepudi** [comment]
@milas and @nicks this can be closed now as it seems to be working now after @nicks https://github.com/tilt-dev/tilt-extensions/pull/282 has been merged? i am using arm64 images without any problem now.

**Comment by leftbin-swarup** [comment]
@milas and @nicks this can be closed now as it seems to be working now after @nicks https://github.com/tilt-dev/tilt-extensions/pull/282 has been merged? i am using arm64 images without any problem now.

**Comment by milas** [comment]
Glad to hear it! Thanks for the reminder 🙂
