### ISSUE TITLE
Make controller-gen crd-options configurable

### ISSUE THREAD

**Issue by nitishm** [tilt-dev/tilt-extensions#129]
In https://github.com/tilt-dev/tilt-extensions/blob/master/kubebuilder/Tiltfile#L15 assumes the defaults used in the kubebuilder initialized Makefile

For cases where the end user needs to add new annotations/options to the controller-gen run command, it would be good to have an option to specify them through the kubebuilder extension.

For instance in my case I need `preserveUnknownFields` to be set to `true`
```
CRD_OPTIONS ?= "crd:trivialVersions=true,preserveUnknownFields=true"
```

**Comment by ellenkorbes** [comment]
hey @nitishm can you see if this works for you?

**Comment by nitishm** [comment]
@ellenkorbes I can try. What would the API format be to pass the options?

**Comment by ellenkorbes** [comment]
@nitishm The same as the command line arguments for `controller-gen`, as a string. I believe for what you want it would be:

`kubebuilder(hello, hello, v1, Hello,  CONTROLLERGEN='crd:trivialVersions=true,preserveUnknownFields=true rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases;')`

**Comment by nitishm** [comment]
Ok - dumb question but how do I build this or use it with the latest tilt release? 😶

**Comment by ellenkorbes** [comment]
Hi @nitishm, to use it you first import the extension into your Tiltfile, then call the function you'd like to use from that extension. In this case, they're both called `kubebuilder`.

So for the example call above, your Tiltfile would look like this:

```python
load('ext://kubebuilder', 'kubebuilder')

kubebuilder(hello, hello, v1, Hello,  CONTROLLERGEN='crd:trivialVersions=true,preserveUnknownFields=true rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases;')
```
