### ISSUE TITLE
Prometheus extension example fails on macOS

### ISSUE THREAD

**Issue by zachgrayio** [tilt-dev/tilt-extensions#130]
output:
```
...
local: tar -C /var/folders/f8/pqx_d6kx5hgdvghjhhf0qd8h0000gn/T/tmp.lBoYMb6e/prometheus-operator-kube-prometheus-v0.5.0 -xzf /Users/user/code/repos/flare/tilt_modules/coreos_prometheus/.tilt-cache/coreos-kube-prometheus-v0.5.0.tar.gz --strip-components=1 --wildcards 'prometheus-operator-kube-prometheus-*/manifests'
 → tar: Option --wildcards is not supported
 → Usage:
 →   List:    tar -tf <archive-filename>
 →   Extract: tar -xf <archive-filename>
 →   Create:  tar -cf <archive-filename> [filenames...]
 →   Help:    tar --help
Successfully loaded Tiltfile (4.120123106s)
Traceback (most recent call last):
  /Users/user/code/repos/flare/Tiltfile:15:1: in <toplevel>
  /Users/user/code/repos/flare/tilt_modules/coreos_prometheus/Tiltfile:176:25: in <toplevel>
  /Users/user/code/repos/flare/tilt_modules/coreos_prometheus/Tiltfile:66:10: in download_files
  <builtin>: in local
Error: command ["sh" "-c" "tar -C /var/folders/f8/pqx_d6kx5hgdvghjhhf0qd8h0000gn/T/tmp.lBoYMb6e/prometheus-operator-kube-prometheus-v0.5.0 -xzf /Users/user/code/repos/flare/tilt_modules/coreos_prometheus/.tilt-cache/coreos-kube-prometheus-v0.5.0.tar.gz --strip-components=1 --wildcards 'prometheus-operator-kube-prometheus-*/manifests'"] failed.
error: exit status 1
```

I haven't traced down the source of this `tar` usage yet to look at a patch but the issue looks as simple as usage of the non-portable `--wildcards` flag which won't work on macOS; perhaps an alternative syntax could be used here (but not sure what other issues might follow).

**Comment by nicks** [comment]
Hmmm....ya, this should be more portable. For now, you might be able to work around this by `brew install coreutils` to get a more recent version of tar (i think the issue is that macos has a very old one by default?)

**Comment by electrofelix** [comment]
The current tar command is just looking to limit extraction to the `manifests` directory, however there is no reason that it can't be modified to extract elsewhere and then copy just the manifests directory as needed. Part of what it's doing with the wildcard is to remove the need to know about version number in the directory structure afterwards by removing that component of the path.

Could also consider just letting it extract the entire contents and not care about limiting it to the manifest as long as the listdir is limited to the correct path it shouldn't matter.

**Comment by milas** [comment]
This extension should now work on macOS without needing GNU coreutils installed.

If you've previously run it and it failed, you might need to `rm -rf ./tilt_modules/coreos_prometheus` from the directory where your `Tiltfile` lives and then `tilt up` again to fetch the updated version.
