### ISSUE TITLE
keep helm resources in order in helm_remote extension

### ISSUE THREAD

**Issue by mehran-prs** [tilt-dev/tilt-extensions#133]
I think the `helm_remote` plugin doesn't keep helm resources in order to apply!

**Comment by nicks** [comment]
Hi @mehran-prs ! Can you give an example of a chart that doesn't work like you expect? Tilt does a fair amount of work to put things in the right order, but it's certainly possible we missed a case!

**Comment by mehran-prs** [comment]
Hi @nicks,
It occurred just one time and after that everything was good, If I faced it again, I'll try to write steps to reproduce it.
I think we can close this issue for now.

**Comment by nicks** [comment]
Thanks @mehran-prs . Will close to now, happy to re-open if you see this again.
