### ISSUE TITLE
git_resource extension broken for valid scheme:// repository URLs with a user

### ISSUE THREAD

**Issue by MikeSouza** [tilt-dev/tilt-extensions#135]
The `git_resource` extension's `git_checkout` has been broken for valid [Git repository URLs](https://gitirc.eu/git-clone.html#URLS) in the latest version (2d72dabfb798de90a2a7197dc7f98ff88822bd75), which added support for specifying git revisions (https://github.com/tilt-dev/tilt-extensions/pull/134). It incorrectly parses URLs starting with a scheme (i.e. `http://`, `ssh://`, `ftp://`) and that specify a `<user>@`, which is a completely valid repository URL.

For example, previous versions of the extension would parse perfectly fine the following repository URLs:
```
git_checkout('https://user@example.com/path/repo.git', 'dest_path')
git_checkout('ssh://user@example.com:54321/path/repo.git', 'dest_path')
```
However, #134 changed `_parse_repository_url()` (https://github.com/tilt-dev/tilt-extensions/commit/2d72dabfb798de90a2a7197dc7f98ff88822bd75#diff-376d4b8dbfc3fc881c2bc14cef747dd7fdd4903926755b1a924c55d571ead355R105-R113) so that it incorrectly splits at the `@` and gives an error like the following when attempting to clone a URL such as `https://user@example.com/path/repo.git`:

```
local: basename https://user .git
local: git clone https://user --recurse-submodules --shallow-submodules dest_path && cd dest_path && git checkout example.com/path/repo.git
Successfully loaded Tiltfile (5.325367799s)
Traceback (most recent call last):
  /some/path/to/Tiltfile:113:4: in <toplevel>
  /some/path/to/Tiltfile:75:15: in all
  /some/path/to/tilt_modules/git_resource/Tiltfile:57:22: in git_checkout
  <builtin>: in local
Error: command ["sh" "-c" "git clone https://user --recurse-submodules --shallow-submodules dest_path && cd dest_path && git checkout example.com/path/repo.git"] failed.
error: exit status 128
```
Notice above how it tries to `git clone https://user`.

**Comment by nicks** [comment]
thanks for the report! oof, i was worried about overloading the '@' character, but maybe there's something simple I can do to make this work

cc @KOGI

**Comment by KOGI** [comment]
I'm entirely open to using a different char, too! Maybe something like `$` might be a better choice. Although, now we have to consider backward compatibility...

**Comment by nicks** [comment]
merged! if you delete the tilt_modules and restart, you should get the new version
