### ISSUE TITLE
Feat: root directory

### ISSUE THREAD

**Issue by kevin-lindsay-1** [tilt-dev/tilt-extensions#147]
I've got some code that I use pretty often when working with nested tiltfiles.

Bit of an edge case, but if you think it's useful feel free to modify it and stick it into the base extensions.

```
def get_root_directory():
  tilt_root_directory = os.getenv('TILT_ROOT_DIRECTORY')

  if tilt_root_directory == None:
    tilt_root_directory = os.getcwd()
    os.putenv('TILT_ROOT_DIRECTORY', tilt_root_directory)
  
  return tilt_root_directory
```

Not really sure what the naming conventions are, but I could make a PR if we like it.

**Comment by landism** [comment]
Is that the same as [config.main_dir](https://docs.tilt.dev/api.html#modules.config.main_dir)?

**Comment by kevin-lindsay-1** [comment]
ooh, shiny! that looks like it was made after I made this util a while ago. I'll check

**Comment by kevin-lindsay-1** [comment]
Yep, it looks like this does the same thing, nice! Thanks @landism!
