### ISSUE TITLE
file_sync_only depends on image resource

### ISSUE THREAD

**Issue by paulcwarren** [tilt-dev/tilt-extensions#150]
Hi there,

I've been attempting to use the `file_sync_only` extension.  It doesn't actually work for me because [this line](https://github.com/tilt-dev/tilt-extensions/blob/7eb35018e760182f7a915abeac6674aefa110956/file_sync_only/Tiltfile#L51) sets up a dependency on a resource using `image`.  

Doesn't this rely on the assumption that the deployment and its image are named the same?  What if I replaced the image with my nginx image; `paulcwarren/nginx`?   My tests seem to indicate this will fail.

Or am I mis-understanding something?

I'm quite happy to submit a PR with a fix for this but I wanted to check my understanding before doing so (I am fairly new to Tilt).

Thanks

**Comment by nicks** [comment]
yep! You've got the diagnosis right, it assumes the deployment + image name are the same. Most straightforward solution is probably to let the caller pass in the deployment name as an argument. maybe we can parse it out of the manifests but that might get hairy.

**Comment by paulcwarren** [comment]
Ok.  Thanks for the confirmation.  Passing it in was my first thought too.  I'll PR something in for you.

**Comment by Mins** [comment]
Also stumbled on this issue and it seems that @MasayaAoyama has already addressed this in the pending PR https://github.com/tilt-dev/tilt-extensions/pull/119

https://github.com/tilt-dev/tilt-extensions/blob/ddb559a0ab958027604d700f5f65ef2da49dccbc/file_sync_only/Tiltfile#L73

**Comment by MasayaAoyama** [comment]
@paulcwarren @nicks 
I fixed the code and test for the file_sync_only extension.

**Comment by nicks** [comment]
merged! thanks @MasayaAoyama !
