### ISSUE TITLE
Feature request: target stage in docker_build_with_restart 

### ISSUE THREAD

**Issue by lhotrifork** [tilt-dev/tilt-extensions#164]
Hi,

For multistage builds it would be helpful if docker_build_with_restart could target a specific stage similar to the normal docker_build https://docs.tilt.dev/api.html#api.docker_build

**Comment by nicks** [comment]
Hi @lhotrifork ! I think it already supports this?

https://github.com/tilt-dev/tilt-extensions/tree/master/restart_process#api

Note the part: **kwargs: will be passed to the underlying `custom_build` call

were you having trouble using it?

**Comment by lhotrifork** [comment]
Maybe I miss-read it but doesn't KWARGS_BLACKLIST block it?
https://github.com/tilt-dev/tilt-extensions/blob/master/restart_process/Tiltfile#L4

**Comment by nicks** [comment]
i think that just applies to the 2nd Dockerfile we use to inject 'entr', not the Dockerfile you're passing in. I can double-check in a bit though.

**Comment by lhotrifork** [comment]
Hi @nicks ,
I just checked it myself. It does work! <3

**Comment by nicks** [comment]
wooo! :tada:
