### ISSUE TITLE
secret: invalid argument error -- passing "client" when expects boolean

### ISSUE THREAD

**Issue by nicksherron** [tilt-dev/tilt-extensions#200]
```bash
$ kubectl create secret generic test-secret --from-file realm.json=./example.json -o=yaml --dry-run=client
Error: invalid argument "client" for "--dry-run" flag: strconv.ParseBool: parsing "client": invalid syntax
See 'kubectl create secret generic --help' for usage.
```

**Comment by nicks** [comment]
Left a comment on the PR

--dry-run=true was deprecated in kubectl v1.18. Here are some good notes on it:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#kubectl-1
https://kubernetes.io/docs/reference/kubectl/conventions/#generators

We'd accept a PR that checked `kubectl version --client` and used the old syntax for old kubectl versions, though!

**Comment by nicksherron** [comment]
thanks for the info! Apparently I had like 4 instances of kubectl in my path and it was using an older one. If I get around to the version check pr I’ll be sure to submit it.

**Comment by nicks** [comment]
| 4 instances of kubectl in my path

:joy: :joy: :joy:

**Comment by nicksherron** [comment]
its gclouds fault lol
