### ISSUE TITLE
[uibutton] cmd_button argv running on load rather than on click / call `tilt args` from uibutton

### ISSUE THREAD

**Issue by jmo-qap** [tilt-dev/tilt-extensions#202]
Love the UI button extension! I would like to make a button that toggles certain config parameters. For example:

```
load('ext://uibutton', 'cmd_button', 'location')

config.define_bool('cache')
cfg = config.parse()
cache = cfg.get('cache',False)

button_icon = 'sync_disabled' if cache else 'sync'
button_text = 'turn caching off' if cache else 'turn caching on'

cmd_button(name='caching-toggle-button',
        argv=["tilt","args","--","--cache="+("false" if cache else "true" ],
        text=button_text,
        location=location.NAV,
        icon_name=button_icon)

local_resource("blah", "echo hello world")
```

However, this causes infinite cycling. It _appears_ that when the cmd_button click runs`tilt args -- --cache=true`, the refreshing tiltfile executes the argv _immediately again_ rather than waiting for the next click thereby starting a cycle. Another way to say this is, `cmd_button` runs the argv command _on load_ rather than _on click_ when `tilt args -- --cache=true` is the source of the tiltfile refresh AND when the UI button has been clicked at least once.

With an even simpler test Tiltfile:
```
load('ext://uibutton', 'cmd_button', 'location')

config.define_bool('cache')
cfg = config.parse()

cmd_button(name='caching-toggle-button',
        argv=["echo", "blah"],
        text='sync',
        location=location.NAV,
        icon_name='sync')

local_resource("blah", "echo food")
```
Steps to reproduce:
1. tilt up
2. open another terminal (2) and `tilt args -- --cache=false` and get expected behavior
3. click button and see `echo blah`
4. in terminal (2), `tilt args -- --cache=false` again and get an invocation of `echo blah` without clicking the button.
5. click the tilt refresh tiltfile button or change a line in the Tiltfile itself and again get an invocation of `echo blah` even without clicking the UI button.

Something about step 3 creates the on load exec of argv.

![Screen Shot 2021-07-08 at 10 11 28 PM](https://user-images.githubusercontent.com/56177725/125026438-73790200-e039-11eb-8e27-4f39cf324474.png)

(I'm on mac and using tilt 0.21.2)

**Comment by nicks** [comment]
thanks for reporting! I have some ideas on this
