### ISSUE TITLE
syncback — fails to verify rsync on linux

### ISSUE THREAD

**Issue by khuynh0** [tilt-dev/tilt-extensions#255]
The syncback extension fails to verify rsync on linux (Manjaro).

I have rsync 3.2.3 installed, but getting this error.
```
→ Could not parse local rsync version (need version >= 3.0.0)
```

Tracked the issue down to the [rsync version regex](https://github.com/tilt-dev/tilt-extensions/blob/master/syncback/verify_rsync.sh#L17) not accounting for differences in outputs for `rsync --version`.

Expects:
```
rsync  version 3.2.3  protocol version 31
```

Receives (note the preceding `v` before `3.2.3`):
```
rsync  version v3.2.3  protocol version 31
```

**Comment by jimsimon** [comment]
Changing the regex used to `^.*version v?([0-9]+\.[0-9]+\.[0-9]+).*$` should fix it.

**Comment by nicks** [comment]
thanks for the report! Ya, if you want to open a PR and take the credit for finding this, that would help! Otherwise I'll try to find time to do it later today.
