### ISSUE TITLE
Add Labels to Helm Remote 

### ISSUE THREAD

**Issue by jay-manday** [tilt-dev/tilt-extensions#299]
Hi there, I wanted to ask to see if we can add the labels API to the Helm Remote extension, we use it heavily to install remote packages like Kafka and Pachyderm and would like to group resources attached to these helm charts with the label api.

https://blog.tilt.dev/2021/08/09/resource-grouping.html

Thanks!

**Comment by Chimney42** [comment]
Hi @jay-manday,
as a quick workaround: have you already tried using the `k8s_resource` function to label the resources after they have been deployed with `helm_remote`?
https://docs.tilt.dev/api.html#api.k8s_resource

For the long-term solution, we'd like to understand your issue a bit better. Could you elaborate a bit more on your use-case? E.g. do you want to label all resources the same for each helmchart, or are there other ways you'd like to group them?

**Comment by jay-manday** [comment]
Hey @Chimney42 thanks for jumping on this! Thank you! It looks like I can indeed attach labels to those resources! Thanks for the suggestion

**Comment by micahlmartin** [comment]
I agree that using the `k8s_resource` after the fact does work, but considering that under the hood `local_resource` is being called it seems to make sense to bubble the `labels` parameter up into `helm_remote`.

**Comment by josegonzalez** [comment]
Just getting to this in my usage, would be nice to not have an uncategorized `helm_resource` in my Tilt ui.
