### ISSUE TITLE
helm_remote doesn't support labels

### ISSUE THREAD

**Issue by jackliusr** [tilt-dev/tilt-extensions#307]
Tilt support Resource Groups by using labels. However helm_remote extension doesn't support labels.

**Comment by lizzthabet** [comment]
hi @jackliusr! you should be able to use the `k8s_resource` function to configure (and add labels) any k8s resources that are defined in your helm chart. would you try that out and let me know if it works for you?

**Comment by jackliusr** [comment]
Thanks.  Yes. it works.
