### ISSUE TITLE
helm_resource: add support for namespaces

### ISSUE THREAD

**Issue by markdingram** [tilt-dev/tilt-extensions#324]
Currently namespace can be provided as one of the flags. However this then isn't passed along to the other helm invocations that follow the install.

(I'll submit a PR?)

**Comment by milas** [comment]
Thanks for the report!

Only global Helm flags will be acceptable for both `helm install` and `helm get manifest`, so I think we'll either need a `global_flags` or an explicit `namespace` arg.

We happily take PRs! (I'll try to get to this tomorrow otherwise 🙃)

**Comment by markdingram** [comment]
fixed by #327
