### ISSUE TITLE
helm_resource: sed error on OSX Catalina

### ISSUE THREAD

**Issue by markdingram** [tilt-dev/tilt-extensions#328]
The use of sed [here](https://github.com/tilt-dev/tilt-extensions/blob/fb6856b332bcb4f257a2f50e4a0c7f255d85dc55/helm_resource/Tiltfile#L76) erros on OSX Catalina (10.15.7) 

```
❯ sed -r
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
```

The version of sed on Monterey (12.1) does now include -r.

Problem is seen on a work machine, so upgrading isn't an option right now - there is a workaround by tweaking the path to use <https://formulae.brew.sh/formula/gnu-sed>.

**Comment by milas** [comment]
Thanks for the report! This should be fixed now, if you run `rm -rf ./tilt_modules/helm_resource` in your project and re-evaluate the Tiltfile, it should work.
