### ISSUE TITLE
Is it okay to use existing tilt extensions in other extensions.

### ISSUE THREAD

**Issue by cyucelen** [tilt-dev/tilt-extensions#37]
I wanted to contribute more tilt extensions to this project but i have a question in mind. Is it okay to include existing tilt extensions in other extensions? For example, i want to use `local_output` extension in my further contributions. Is it possible or should i inline it?

**Comment by maiamcc** [comment]
Good question! For now you should inline it--though if this functionality would be useful to you, you should leave a +1/comment with your usecase in https://github.com/tilt-dev/tilt/issues/3452.

**Comment by maiamcc** [comment]
Whoops @cyucelen I led you astray, the issue you actually want to be watching is https://github.com/tilt-dev/tilt/issues/3472 (ty @nicks). The one I linked before is a slightly different problem.

**Comment by maiamcc** [comment]
This should be allowed as of [the latest release](https://github.com/tilt-dev/tilt/releases/tag/v0.15.0) -- let us know if you run into any trouble!
