### ISSUE TITLE
helm_resource fails if chart install resources in other namespaces

### ISSUE THREAD

**Issue by bamorim** [tilt-dev/tilt-extensions#374]
If I do, for example:

```starlark
helm_repo("prometheus-community", "https://prometheus-community.github.io/helm-charts")

helm_resource(
    "kube-prometheus-stack",
    "prometheus-community/kube-prometheus-stack",
    namespace = "o11y",
    flags = [
        '--version', '34.8.0',
        '--values', os.path.join(this_dir, "kube-prometheus-stack.yaml")
    ]
)
```

This will fail because `kube-prometheus-stack` install some things in the namespace `kube-system`, so `helm get manifest --namespace o11y kube-prometheus-stack | kubectl get --namespace o11y -oyaml -f -` fails with:

```
the namespace from the provided object "kube-system" does not match the namespace "o11y". You must pass '--namespace=kube-system' to perform this operation.
the namespace from the provided object "kube-system" does not match the namespace "o11y". You must pass '--namespace=kube-system' to perform this operation.
the namespace from the provided object "kube-system" does not match the namespace "o11y". You must pass '--namespace=kube-system' to perform this operation.
the namespace from the provided object "kube-system" does not match the namespace "o11y". You must pass '--namespace=kube-system' to perform this operation.
the namespace from the provided object "kube-system" does not match the namespace "o11y". You must pass '--namespace=kube-system' to perform this operation.
```

I don't know what the best approach would be. Maybe we should get all manifests  with defined namespaces and get from that namespace instead?

**Comment by nicks** [comment]
I investigated this a bit. There's a bunch of overlapping problems with this chart that make this difficult to fix. Basically:

1) This chart has unusually complex namespacing semantics. Some resources explicitly specify kube-system. Some resources inherit the namespace from the chart namespace. Some resources inherit the namespace from the default kubecontext (see: https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/servicemonitor.yaml#L8)

2) In particular, Helm chart namespace and Helm default kubecontext namespace are slightly different

3) `helm get manifest` fetches all the resources in the chart. Helm chart namespace is filled in. Helm default kubecontext namespace is not filled in.

4) `kubectl get --namespace [namespace] -oyaml -f -` uses the `--namespace` flag as both "default kubecontext namespace" and as "please validate all the returned resources match this namespace"

I could probably make the case that the `kubectl` behavior is incorrect here. The `You must pass '--namespace=%s'` error probably isn't intended for this use-case...

I could also probably make the case that `helm get manifest` should be doing namespace defaulting, and the fact that it's not is it's own bug...

**Comment by nicks** [comment]
we might be able to workaround this with something like:

```
kubectl config view --minify >> out.tmp
KUBECONFIG=./out.tmp kubectl config set-context --current --namespace=o11y
KUBECONFIG=./out.tmp kubectl get -oyaml -f -
```

**Comment by Fresa** [comment]
> I investigated this a bit. There's a bunch of overlapping problems with this chart that make this difficult to fix. Basically:
> 
> 1. This chart has unusually complex namespacing semantics. Some resources explicitly specify kube-system. Some resources inherit the namespace from the chart namespace. Some resources inherit the namespace from the default kubecontext (see: https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/servicemonitor.yaml#L8)
> 2. In particular, Helm chart namespace and Helm default kubecontext namespace are slightly different
> 3. `helm get manifest` fetches all the resources in the chart. Helm chart namespace is filled in. Helm default kubecontext namespace is not filled in.
> 4. `kubectl get --namespace [namespace] -oyaml -f -` uses the `--namespace` flag as both "default kubecontext namespace" and as "please validate all the returned resources match this namespace"
> 
> I could probably make the case that the `kubectl` behavior is incorrect here. The `You must pass '--namespace=%s'` error probably isn't intended for this use-case...
> 
> I could also probably make the case that `helm get manifest` should be doing namespace defaulting, and the fact that it's not is its own bug...

This seems to still be a problem when namespaces are not explicitly defined per manifest. Maybe solve this by looking for manifests without explicitly defined namespaces and explicitly use the namespace used for `helm upgrade` for those resources when piping to `kubectl get -oyaml -f -`?
