### ISSUE TITLE
recent helm_resource PR broke my setup

### ISSUE THREAD

**Issue by kalmant** [tilt-dev/tilt-extensions#379]
#### The situation

My Tilt setup suddenly stopped working and I was able to track it down to this change: https://github.com/tilt-dev/tilt-extensions/commit/3f083db5fb35f7fbbf897731a49ce95c6711901a / https://github.com/tilt-dev/tilt-extensions/pull/376

#### Background
I'm using `helm_resource` to deploy a "custom" nginx ingress to a particular namespace. This "custom" chart uses an official ingress-nginx chart as a dependency and "extends" it, by having a couple of configmaps in `templates`. This way we can deploy using the official chart but also deploy a couple of custom configmaps at the same time.

I'm using `helm_resource` this way:
`helm_resource('ingress-nginx-local', 'somepath/ingress-nginx-custom',namespace='ingress-nginx-local', flags=['-f', 'somepath/ingress-nginx-local.yaml'])`
(the namespace already exists when this runs)

#### What happens

I get an "Update error" in Tilt (I've attached the logs included with some redactions and a sample configmap template) when this resource gets deployed, although it looks like everything is properly deployed to the cluster (including those configmaps in the desired namespace).

By downgrading to the previous version (commit `5a806c1f072ab26c29b03730ad738877c260a8c9`) of `helm_resource` I am able to "fix" the issue.

#### **Note for future readers**
Following the steps outlined in the [docs](https://docs.tilt.dev/extensions.html#modifying-the-default-extensions-locally) I am able to run Tilt with a previous extension version to keep things green until a more proper solution is found.

[deploy_output.txt](https://github.com/tilt-dev/tilt-extensions/files/8441817/deploy_output.txt)
[redacted_configmap_yaml.txt](https://github.com/tilt-dev/tilt-extensions/files/8441821/redacted_configmap_yaml.txt)

**Comment by nicks** [comment]
hmmmm...i'm having trouble reproducing this. but let's roll the PR back for now until we can investigate further...

**Comment by kalmant** [comment]
> hmmmm...i'm having trouble reproducing this. but let's roll the PR back for now until we can investigate further...

If you can't reproduce it, I can try to put together a repro (hopefully tomorrow).

**Comment by nicks** [comment]
ok, the pr has been rolled back. will fiddle a bit more with a repro case but if you can come up with one easily that would help!

**Comment by kalmant** [comment]
I sent a repro on the k8s Slack in a DM.

**Comment by nicks** [comment]
lol, i see the problem. This chart renders to this:

```
# Source: ingress-nginx-custom/templates/configmap-sample.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-configmap
  namespace: 
  labels:
    helm.sh/chart: ingress-nginx-custom-1.0.0
data:
  sample: "true"
```

which my defaulter script is parsing incorrectly (namespace is blank)

**Comment by Canas** [comment]
This error appeared today for me. Looking at the last update 4 days ago the PR that broke namespace was applied again?

**Comment by nicks** [comment]
(meanwhile, there's an api to pin old extension versions here - https://docs.tilt.dev/extensions.html#managing-your-own-extension-repo)
