### ISSUE TITLE
configmap_create runs unexpectedly multiple times

### ISSUE THREAD

**Issue by majelbstoat** [tilt-dev/tilt-extensions#383]
I have a configmap_create statement inside a method for deploying a go service:

```python
def go_service(name):
    service_path = 'services/%s/app' % name
    bin_path = 'services/%s/dist/%s' % (name, name)

    configmap_create(name, from_env_file='services/%s/env/dev.env' % name)

    local_resource(
        name='compile-%s' % name,
        cmd='CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o %s pinian.io/%s/app' % (
            bin_path, name),
        deps=[service_path]
    )

    docker_build_with_restart(
        ref='us-docker.pkg.dev/pinian-app/pinian/%s-dev' % name,
        context='.',
        dockerfile='devops/docker/dev-go.dockerfile',
        live_update=[
            sync(bin_path, '/go/bin/pinian-service'),
        ],
        only=[bin_path],
        entrypoint=['/go/bin/pinian-service']
     )
    k8s_yaml('services/%s/k8s/dev.yaml' % name)
    k8s_resource(name, resource_deps=['compile-%s' % name])

go_service("core-api")
go_service("images-api")
```
Essentially, create a config map, compile the binary, build an image, put the image in k8s.

When I change a go file, the relevant service is live updated, and everything's great.

However, when I change, for example, `services/core-api/env/dev.env`, I see logs for the rebuilding of every config map:

```
local: kubectl create configmap core-api --from-env-file services/core-api/env/dev.env -o=yaml --dry-run=client
local: kubectl create configmap images-api --from-env-file services/images-api/env/dev.env -o=yaml --dry-run=client
```

My expectation is that when changing `services/core-api/env/dev.env`, only the core-api configmap would be rebuilt. Have I configured this incorrectly, or is that a bug?

**Comment by nicks** [comment]
Hi @majelbstoat !! Ya, I can explain what's happening here:

1) When one dev.env changes, it re-executes the whole tiltfile.
2) When the tiltfile re-executes, kubectl will generate new YAML.
3) Tilt will diff that YAML against what you deloyed last, and determine whether it needs to be redeployed.

I wouldn't be too concerned about all the `kubectl create --dry-run` calls, because they're only generating YAML, not talking to your cluster.

Is it causing any slowness, or are you more worried about the log spam?

**Comment by majelbstoat** [comment]
Just the log spam, primarily.

And I was concerned that if they reloaded, all the dependent services would also restart, but https://github.com/tilt-dev/tilt/issues/3895 tells me that’s not a problem at least for now 😂
