### ISSUE TITLE
Use builtin for uibutton extension

### ISSUE THREAD

**Issue by lianmakesthings** [tilt-dev/tilt-extensions#384]
On Windows, adding `cmd_button`s to the Tiltfile causes evaluation to take several seconds longer per button.

```
Trying to use cmd_button but it seems like each use of it adds several seconds to the tiltfile parsing. Is this supposed to happen? It wouldn't be too bad if it was just on initial load but it happens on any changes to any resources too.
Looks like the apply it calls is very slow eg:
verb="PATCH" URI="/apis/tilt.dev/v1alpha1/cmds/btn-button1?fieldManager=kubectl-client-side-apply" latency="6.7736ms" userAgent="Go-http-client/2.0"
```
```
load('ext://uibutton', 'cmd_button', 'location')
cmd = ['hostname']

local_resource('local', cmd='hostname')

cmd_button('button1',argv=cmd,location=location.NAV)
cmd_button('button2',argv=cmd,location=location.NAV)
cmd_button('button3',argv=cmd,location=location.NAV)
cmd_button('button4',argv=cmd,location=location.NAV)
```
```
> tilt up --stream --port 10351
Tilt started on http://localhost:10351/
v0.27.0, built 2022-04-01

Initial Build
Loading Tiltfile at: C:\temp\tiltdev\Tiltfile
 → uibutton.tilt.dev/button1 created
 → cmd.tilt.dev/btn-button1 created
 → uibutton.tilt.dev/button2 created
 → cmd.tilt.dev/btn-button2 created
 → uibutton.tilt.dev/button3 created
 → cmd.tilt.dev/btn-button3 created
 → uibutton.tilt.dev/button4 created
 → cmd.tilt.dev/btn-button4 created
Successfully loaded Tiltfile (45.6043661s)
```

We are currently unable to reproduce this behaviour on our local machines
Currently, the `cmd_button` extension shells out to `tilt appl`y which is probably causing unnecessary overhead.
Our best guess is, that using the builtin instead of shelling should cut down on processes spawned.

**Comment by lianmakesthings** [comment]
Another user reports the same issue and their workaround

```
Hey, I was wondering what the impact would be of removing all the local() invocations in https://github.com/tilt-dev/tilt-extensions/blob/master/uibutton/Tiltfile and hardcoding the "startAfter": _now() to a fixed timestamp.
My problem is that the local invocations are slow on my windows machine, adding 1 button adds +- 2 seconds loading time to the tiltfile because the local command starts powershell and this process is slow.
(measure-command { powershell Get-Date (Get-Date).ToUniversalTime() -UFormat '+%Y-%m-%dT%H:%M:%S.000000Z' }).TotalSeconds takes +- 1.2 seconds on my PC at work and at home it takes +- 0.4 seconds.
Maybe the local command calls can be refactored to something native in the Tilt CLI or in the starlark language
I've tried the above (removing the local() invocations) and the Tiltfile is fast again and the button still works
```

**Comment by milas** [comment]
This will also fix #193 because buttons created with built-ins are automatically GC'd by the engine.

**Comment by jbadlato** [comment]
@landism I also took a stab at using the builtin and ran into the same issue.  How complex would it be to add support for metav1.Time? Is it simple enough for an external contributor to give a try?

**Comment by nicks** [comment]
i thought the Time stuff was for an obsolete version of the API and everything will work fine without it now.

**Comment by jbadlato** [comment]
@nicks Ah, does that mean we don't need the `start_after` field at all anymore? It does seem to work fine for me without it, but I wasn't sure exactly what it was there for to begin with, so was afraid to blindly remove it.  

If that's the case, I can probably open a PR for this

**Comment by nicks** [comment]
@jbadlato yep, that's exactly what I mean 😊

**Comment by landism** [comment]
At the risk of being pedantic (or, just to put my understanding in writing):
`start_after` was added to cover the case described in [this comment](https://github.com/tilt-dev/tilt/pull/4600#discussion_r641702756).

IIUC, `start_after` is still useful for that case, and not entirely obsolete.

However, the uibutton extension forces the button and command to have the same name, which avoids that case in the first place, so the extension doesn't need to set the field.
