### ISSUE TITLE
helm_resource fails if chart installs in a namespace other than default

### ISSUE THREAD

**Issue by eengelking** [tilt-dev/tilt-extensions#399]
When attempting to pass the `namespace` variable for `helm_resource`, I can confirm the namespace is created and pods come online as expected.  However, the Tilt UI shows an error:

```bash
     Running cmd: ['helm', 'get', 'manifest', '--namespace', 'scan', 'scandev']
     Running cmd: ['kubectl', 'get', '-oyaml', '-f', '-']   <-- MISSING NAMESPACE FLAG
     error: error parsing STDIN: error converting YAML to JSON: yaml: line 6: mapping values are not allowed in this context
     Traceback (most recent call last):
       File "/home/<mydir>/.local/share/tilt-dev/tilt_modules/github.com/tilt-dev/tilt-extensions/helm_resource/helm-apply-helper.py", line 105, in <module>
         completed.check_returncode()
       File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.13_1/lib/python3.9/subprocess.py", line 460, in check_returncode
         raise CalledProcessError(self.returncode, self.args, self.stdout,
     subprocess.CalledProcessError: Command '['kubectl', 'get', '-oyaml', '-f', '-']' returned non-zero exit status 1.   <-- MISSING NAMESPACE FLAG
```

When I remove the `namespace` flag from `helm_resource`, Tilt deploys as expected in the `default` namespace and the UI shows no errors.

After looking at the `helm-apply-helper.py` file, I believe I understand the issue:

```bash
if namespace:
  install_cmd.extend(['--namespace', namespace])
  get_cmd.extend(['--namespace', namespace])
```

The `if namespace` check includes an extend for `install_cmd` and `get_cmd` if the namespace variable is set, but does not include this option for the `kubectl_cmd` variable.

I wanted to check that my logic made sense before submitting a PR for this, and will be happy to do so once someone has confirmed my logic to be true/false.

Thanks!

**Comment by nicks** [comment]
welcome to the wonderful world of namespace defaulting! I don't think it's quite as simple as that, because 'chart namespace' and 'kubectl namespace' can be different. See discussion here: https://github.com/tilt-dev/tilt-extensions/issues/374#issuecomment-1089271912

Can you post your helm chart? i suspect something else is going wrong.

**Comment by eengelking** [comment]
Unfortunately I can't share the chart ATM, however based on your feedback I've tested a few other public charts and they do appear to work correctly, so thank you for the clarification.  I'll research my chart further to see what might be causing the issue.

As far as the error re: YAML is concerned, I ran the command `helm get manifest --namespace scan scandev | kubectl get -oyaml -f -` to see what the actual error was.  I found that I receive a significant number of errors:

```bash
Error from server (NotFound): serviceaccounts "api" not found
Error from server (NotFound): secrets "api-secret" not found
Error from server (NotFound): secrets "db-secret" not found
Error from server (NotFound): secrets "registry-key" not found
Error from server (NotFound): configmaps "api-configmap" not found
Error from server (NotFound): configmaps "ui-configmap" not found
Error from server (NotFound): services "api" not found
Error from server (NotFound): services "ui" not found
Error from server (NotFound): deployments.apps "api" not found
Error from server (NotFound): deployments.apps "ui" not found
Error from server (NotFound): ingresses.networking.k8s.io "api" not found
Error from server (NotFound): ingresses.networking.k8s.io "ui" not found
```

However, when I ran the command `helm get manifest --namespace scan scandev | kubectl --namespace scan get -oyaml -f -`, it worked without issue.  This is what lead me to believe the namespace call was the culprit, as kubectl is calling either the default namespace or whatever namespace is set via the context.

**Comment by eengelking** [comment]
I've been able to update my Helmfile to resolve the issue.  Thank you for the feedback.
