### ISSUE TITLE
shareing tilt-extensions from on-prem GitLab instance

### ISSUE THREAD

**Issue by opvasger** [tilt-dev/tilt-extensions#427]
Hello - I've defined a few extensions that I want to share internally at work. Is this possible somehow?

I've attempted to do it using `v1alpha1.extension_repo` and `v1alpha1.extension`, somewhat like this:

```
v1alpha1.extension_repo(name="ci-cd", url="https://HOSTNAME/GROUP/ci-cd")
v1alpha1.extension(name="a", repo_name="ci-cd")
load("ext://a","dotnet_build");
load("ext://a","vue_build");

allow_k8s_contexts("docker-desktop");

vue_build(ref="client",context="client")
dotnet_build(ref="server", context="server")

k8s_yaml("k8s.yml");
k8s_resource(workload = "server", port_forwards = "5000:5000");
k8s_resource(workload = "client", port_forwards = "3000:3000");
```

**Comment by nicks** [comment]
Hi! This issue report doesn't have enough information to repro your issue, or even understand what question you're asking. Can you post:
- a repro case
- what you expected to happen
- what actually happened

This guide on how to debug extension loading might also help: https://docs.tilt.dev/extensions.html#debugging-extension-loading-with-the-cli

**Comment by opvasger** [comment]
well, I guess it really comes down to a question - can I host my tilt-extensions from GitLab instead of Github? if so, do you have a guide or some docs about it? :sunny:

**Comment by nicks** [comment]
I can't think of any reason it wouldn't work for any git repo.
