### ISSUE TITLE
helm_resource: Support to specify a specific version of the chart to install

### ISSUE THREAD

**Issue by sivasamyk** [tilt-dev/tilt-extensions#448]
While using `helm_resource` to install a chart from remote repo, currently, there is no option to specify the specific version of the chart to install. Similar option exists for `helm_remote`.

**Comment by nicks** [comment]
helm_resource has a flags parameter that lets you pass arbitrary flags to the install. So this looks like:

```
helm_resource(..., flags=['--version=2'])
```
