### ISSUE TITLE
[Bug] `helm_resource` works locally but times-out on CI server

### ISSUE THREAD

**Issue by rrmistry** [tilt-dev/tilt-extensions#493]
The `helm_resource` works great in local environment.

But when we run Tilt in CI mode with `tilt ci`, then the `helm_resource` times out with no log messages or updates. Not even `--debug` flag prints any useful information.

We suspect this has to do with Tilt not loading or processing the extension properly.

We ensured that `python3` pre-requisite for `helm_resource` exists on the CI agent before `tilt ci` runs

**Comment by nicks** [comment]
Do you have a repo that demonstrates the problem?

there's not really enough information here for us to look into anything. we have many integration tests that use `helm_resource` and other tilt extensions in ci.

**Comment by rrmistry** [comment]
Closing this because the issue stopped occurring now.

We suspect this has to do with dependency cycles but not sure.

Unfortunately, there is no additional capacity available to create a reproducible `Tiltfile` because the issue only happened on CI system, and even running `tilt ci` locally did not produce the issue.
