### ISSUE TITLE
helm_remote not using  provided namespace

### ISSUE THREAD

**Issue by jtinspire** [tilt-dev/tilt-extensions#506]
helm_remote is not respecting the parameter provided for 'namespace'.  The deployment keep happening to default namespace.
Example : 

```
load('ext://helm_remote', 'helm_remote')

k8s_yaml(
    helm_remote(
        'postgres',
        namespace='jaytripathi',
        repo_name='postgres',
        repo_url='https://romanow.github.io/helm-charts/',
    ),
    allow_duplicates=True
)
```

**Comment by nicks** [comment]
do you know if this is a recent regression?

**Comment by abdulvirta** [comment]
Yes this seems to be a very recent regression as of this morning. Might be related to this change that went 5 hours ago.
https://github.com/tilt-dev/tilt-extensions/blob/master/helm_remote/Tiltfile

**Comment by abdulvirta** [comment]
Btw, is helm_resource preferred to use instead of helm_remote? should we switch to helm_resource? and just wondering what is the main difference and why helm_resources is preferred?

**Comment by jtinspire** [comment]
Sorry late to respond. But this is resolved now with above revert.

**Comment by abdulvirta** [comment]
Thanks! Just a general question, which one is more recommended to use helm_resource or helm_remote? just trying to figure out which one is more supported and if there are any differences?
