### ISSUE TITLE
helm_remote failing with OCI repository

### ISSUE THREAD

**Issue by agustingarciaflores** [tilt-dev/tilt-extensions#575]
Hi everyone,

I was trying to use the `helm_remote` extension with one of our OCI repos in ECR. This is the part of the Tiltfile where I load the extension and reference our repository 

```
load('ext://helm_remote', 'helm_remote')

# Note that .helm is in the .tiltignore!
helm_remote('[REPO_NAME]', repo_url='oci://[REDACTED].dkr.ecr.us-east-1.amazonaws.com/charts')
```

And I'm getting the following error:

```
ERROR: Traceback (most recent call last):
  /Users/agus/projects/one/local_development/examples/nucleus_remote_chart/Tiltfile:4:12: in <toplevel>
  /Users/agus/Library/Application Support/tilt-dev/tilt_modules/github.com/tilt-dev/tilt-extensions/helm_remote/Tiltfile:133:31: in helm_remote
Error in local: command "helm repo add [REPO_NAME]' oci://[REDACTED].dkr.ecr.us-east-1.amazonaws.com/charts')" failed.
error: exit status 1
stdout:

stderr:
Error: looks like "oci://[REDACTED].dkr.ecr.us-east-1.amazonaws.com/charts')" is not a valid chart repository or cannot be reached: object required
```

Seems like the extension is trying to make use of `helm repo add` which is not supported by Helm for OCI repos according to the [docs](https://helm.sh/docs/topics/registries/).

**Comment by nicks** [comment]
i thought the way we set this up was that you put the oci:// identifier in the repo_name, see - https://github.com/tilt-dev/tilt-extensions/pull/458

**Comment by agustingarciaflores** [comment]
You are 100% right @nicks, somehow I missed that even thought I looked at that PR like 3 different times. One of those days I guess. My bad, my most sincere apologies, sorry for the distraction!
