### ISSUE TITLE
custom_build_with_restart does not pass signals to wrapped process

### ISSUE THREAD

**Issue by jscheel** [tilt-dev/tilt-extensions#577]
I'm using `custom_build_with_restart` in conjunction with a k8s_resource. I've been testing graceful shutdowns, and noticed that the custom_build that is created does not actually forward signals to the wrapped process. Docker relies on the entrypoint having pid=1, but with the wrapper, the process that actually needs to handle the signals no longer has that pid.

**Comment by nicks** [comment]
Hmm... sorry to hear you're having trouble. Can you provide more specific repro steps on what you're trying to do?

When you say "the custom_build that is created", do you mean the process building the image or the entry point of the result image?

When you say "forward signals", which signals? the signals from the kubelet as part of pod shutdown ? The signals that the cancel button in the tilt UI sends? A manual process that sends signals some other way?

**Comment by nicks** [comment]
ya, that seems reasonable to me

**Comment by jscheel** [comment]
@nicks just added a PR for it
