### ISSUE TITLE
dotenv docs?

### ISSUE THREAD

**Issue by robcresswell** [tilt-dev/tilt-extensions#596]
The dotenv docs are very... minimal. Do you have any examples for how to use the read env vars? Is there any debugging handles I can hook into? This extension assumes a ton about how much someone knows Tilt

**Comment by nicks** [comment]
did you see the test? https://github.com/tilt-dev/tilt-extensions/blob/master/dotenv/test/Tiltfile#L3

there's not really much to say!

**Comment by robcresswell** [comment]
Not sure I agree with that. Took me a while to figure out I could use `verbose=True` & `showValues=True` (I got the casing wrong at first, and the error confused me) and how to use os.getenv() as part of a docker_build to get some value out of the extension.
