### ISSUE TITLE
Escape Characters getting passed as part of the cmd string when using local

### ISSUE THREAD

**Issue by kayafzal** [tilt-dev/tilt-extensions#613]
Hey I am running a command under local that passes special characters, so to bypass the tilt error I am adding \" to add quotes around them. However when running the the command the the backslashes are getting passed as part of the string. Is there any way to bypass this?

Here is an example of what I mean:

`local("vault login --format json -method=ldap username=test password=\"T32,!5dt\"", echo_off=True, quiet=True)`

What I expect to be passed to the command prompt:
`vault login --format json -method=ldap username=test password="T32,!5dt"`

What is actually getting passed 
`vault login --format json -method=ldap username=test password=\"T32,!5dt\"`

**Comment by nicks** [comment]
hmmm...i was unable to reproduce this problem. here are the steps i tried:

Tiltfile:
```
local("echo '\"hi\"' > output.txt")
```

Run: `tilt ci`
Run: `cat output.txt`

Result:
`"hi.txt"`

**Comment by kayafzal** [comment]
Hey Nick,

Apologies yes it was only showing adding the backslash as part of the return error. I have managed to get this working now. Thank you for taking the time to have a look.

I'll close this now
