### ISSUE TITLE
helm_remote creates a namespace

### ISSUE THREAD

**Issue by nicks** [tilt-dev/tilt-extensions#72]
Currently, helm_remote calls namespace_create to create a namespace

https://github.com/tilt-dev/tilt-extensions/blob/master/helm_remote/Tiltfile#L62

It's understandable why it does this! Helm 2 also does this. The behavior was extremely controversial, and was removed in Helm 3.

For discussion, see:
https://helm.sh/docs/faq/
https://github.com/helm/helm/issues/5753

It also creates problems where if you try to create two helm charts in the same namespace, tilt will fail (due to the new duplicate yaml check)

I think there are a couple ways we can move forward with this. I think my suggestion is to add a create_namespace flag (similar to Helm3's --create-namespace), but i'm not sure if the default should be True (for backwards-compatibility) or False (to be more forward-looking to what Helm3 does)

What do others think? 

cc @maiamcc as exterminator this week 
cc @KOGI as the author of this extension

**Comment by KOGI** [comment]
My vote is for defaulting it to false. `helm_remote` can include some logic that only sets it to true if a value was passed to its `namespace` argument.
