### ISSUE TITLE
helm_remote '|| true' on windows

### ISSUE THREAD

**Issue by aphofstede** [tilt-dev/tilt-extensions#74]
See comment in relevant PR: https://github.com/tilt-dev/tilt-extensions/pull/58#discussion_r474616048
The command in `helm_remote\Tiltfile:~111` containing `|| true` doesn't work by default on Windows. Changing to `|| exit 0` appears to work.

**Comment by nicks** [comment]
Ack I'm not sure how I missed this! Lemme test it on my windows box to be sure there's not something wrong with my env
