### ISSUE TITLE
min_k8s_version extension does not handle Kubernetes version from Docker for Mac

### ISSUE THREAD

**Issue by detiber** [tilt-dev/tilt-extensions#82]
Kubernetes version being returned from the integrated Kubernetes on my Docker for Mac install is v1.16.6-beta.0, which results in an error when trying to use a Tiltfile that uses the min_k8s_version extension. 

Looks to be related to: https://github.com/tilt-dev/tilt-extensions/blob/3ad0a2572e325e96108cd1242876fdc03af79cf5/min_k8s_version/Tiltfile#L25

**Comment by nicks** [comment]
thanks for the report! ya, should be an easy fix

**Comment by maiamcc** [comment]
just to confirm expected behavior: v1.16.6 < v1.16.6-beta.0 < 1.16.6-beta1 < 1.16.7 ?

**Comment by detiber** [comment]
@maiamcc That seems reasonable to me
